import { StyleSheet } from 'react-native';

export const COLORS = {
  orange: '#E8622A',
  teal: '#3ABFBF',
  white: '#FFFFFF',
  offWhite: '#F8F9FA',
  text: '#24345A',
  textLight: '#6B6B6B',
  textLighter: '#999999',
  border: '#D9D9D9',
  background: '#F5F3EF',
  yellow: '#F7C600',
  blueBorder: '#2298F0',
};

export const FONT_REGULAR = 'Montserrat-Regular';
export const FONT_SEMIBOLD = 'Montserrat-SemiBold';
export const FONT_BOLD = 'Montserrat-Bold';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 100,
    backgroundColor: COLORS.background,
  },

  titleSection: {
    alignItems: 'center',
    marginBottom: 20,
    marginTop: 4,
  },
  title: {
    fontSize: 20,
    fontFamily: FONT_BOLD,
    color: COLORS.orange,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },

  summaryCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 16,
    marginBottom: 20,
    marginTop: 10,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
  },
  summaryTopTitle: {
    fontSize: 18,
    fontFamily: FONT_BOLD,
    color: COLORS.orange,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 18,
  },
  summaryIdentityRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  summaryAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.orange,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
    marginTop: 2,
  },
  summaryAvatarText: {
    fontFamily: FONT_BOLD,
    fontSize: 17,
    color: COLORS.white,
  },
  summaryNameBlock: {
    flex: 1,
  },
  summaryName: {
    fontFamily: FONT_BOLD,
    fontSize: 17,
    color: COLORS.text,
    marginBottom: 8,
  },
  summaryChips: {
    flexDirection: 'row',
    gap: 8,
  },
  summaryChip: {
    backgroundColor: '#F0F0F0',
    borderRadius: 12,
    paddingVertical: 3,
    paddingHorizontal: 10,
  },
  summaryChipText: {
    fontFamily: FONT_REGULAR,
    fontSize: 12,
    color: COLORS.textLight,
  },
  summaryAddressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
  },
  summaryAddressText: {
    fontFamily: FONT_REGULAR,
    fontSize: 12,
    color: COLORS.textLighter,
    flex: 1,
  },
  summaryDivider: {
    height: 1,
    backgroundColor: '#EBEBEB',
    marginBottom: 16,
  },
  summaryBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingVertical: 4,
  },
  bmiBlock: {
    alignItems: 'center',
    gap: 8,
  },
  bmiCircle: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: COLORS.yellow,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bmiValue: {
    fontFamily: FONT_BOLD,
    fontSize: 22,
    color: COLORS.text,
  },
  bmiLabel: {
    fontFamily: FONT_SEMIBOLD,
    fontSize: 13,
    color: COLORS.textLight,
    textAlign: 'center',
  },
  qrCodeContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },

  sectionCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#D9D9D9',
    elevation: 1,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
  },
  sectionTitle: {
    fontSize: 14,
    fontFamily: FONT_BOLD,
    color: COLORS.textLight,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 20,
  },

  twoColumnRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 14,
  },
  fieldColumn: {
    flex: 1,
  },
  fieldLabel: {
    fontFamily: FONT_SEMIBOLD,
    fontSize: 13,
    color: COLORS.textLight,
    marginBottom: 6,
  },
  fieldValuePill: {
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  fieldValueText: {
    fontFamily: FONT_REGULAR,
    fontSize: 15,
    color: '#5E6E8A',
  },
  chevronBubble: {
    width: 28,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#D3D3D3',
    alignItems: 'center',
    justifyContent: 'center',
  },

  textInputReadonly: {
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    fontFamily: FONT_REGULAR,
    fontSize: 15,
    color: '#5E6E8A',
  },

  subsectionLabel: {
    fontFamily: FONT_SEMIBOLD,
    fontSize: 12,
    color: COLORS.textLight,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginTop: 4,
    marginBottom: 10,
  },
  sectionDivider: {
    height: 1,
    backgroundColor: '#F0F0F0',
    marginVertical: 16,
  },
  antecedentSection: {
    marginTop: 16,
  },
  antecedentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  antecedentTitle: {
    fontFamily: FONT_SEMIBOLD,
    fontSize: 13,
    color: COLORS.textLight,
  },
  addAntecedentBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: COLORS.orange,
    alignItems: 'center',
    justifyContent: 'center',
  },
  antecedentEmpty: {
    fontFamily: FONT_REGULAR,
    fontSize: 12,
    color: COLORS.textLighter,
    fontStyle: 'italic',
  },

  tagsWrap: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  tag: {
    borderRadius: 12,
    backgroundColor: COLORS.orange,
    paddingVertical: 6,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  tagText: {
    fontFamily: FONT_REGULAR,
    fontSize: 12,
    color: COLORS.white,
  },
  tagClose: {
    color: COLORS.white,
    fontSize: 14,
    fontFamily: FONT_SEMIBOLD,
    marginLeft: 4,
  },

  fileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    paddingLeft: 4,
  },
  fileName: {
    marginLeft: 10,
    fontFamily: FONT_REGULAR,
    fontSize: 13,
    color: COLORS.text,
  },

  // ─── Upload Modal ─────────────────────────────────────────────────────────
  uploadModalSheet: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 24,
    paddingBottom: 36,
  },
  uploadModalTitle: {
    fontFamily: FONT_BOLD,
    fontSize: 18,
    color: COLORS.text,
    textAlign: 'center',
    marginBottom: 6,
  },
  uploadModalSubtitle: {
    fontFamily: FONT_REGULAR,
    fontSize: 13,
    color: COLORS.textLight,
    textAlign: 'center',
    marginBottom: 24,
  },
  uploadModalPickBtn: {
    backgroundColor: COLORS.orange,
    borderRadius: 22,
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 12,
  },
  uploadModalPickBtnText: {
    fontFamily: FONT_SEMIBOLD,
    fontSize: 15,
    color: COLORS.white,
  },
  uploadModalCancelBtn: {
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadModalCancelText: {
    fontFamily: FONT_SEMIBOLD,
    fontSize: 15,
    color: COLORS.textLight,
  },
  uploadModalSearchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 22,
    paddingHorizontal: 12,
    height: 40,
    marginBottom: 8,
    gap: 8,
  },
  uploadModalSearchInput: {
    flex: 1,
    fontFamily: 'Montserrat-Regular',
    fontSize: 14,
    color: '#24345A',
  },
  uploadModalOptionsList: {
    maxHeight: 220,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 12,
  },
  uploadModalOptionItem: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  uploadModalOptionText: {
    fontFamily: 'Montserrat-Regular',
    fontSize: 14,
    color: '#24345A',
  },
  uploadModalSelectedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E8622A',
    borderRadius: 22,
    paddingHorizontal: 14,
    height: 44,
    marginBottom: 16,
    gap: 8,
  },
  uploadModalSelectedText: {
    flex: 1,
    fontFamily: 'Montserrat-SemiBold',
    fontSize: 14,
    color: '#E8622A',
  },
  uploadModalStepLabel: {
    fontFamily: FONT_SEMIBOLD,
    fontSize: 12,
    color: COLORS.textLight,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  uploadModalNameInput: {
    height: 48,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    backgroundColor: '#F8F8F8',
    paddingHorizontal: 16,
    fontFamily: FONT_REGULAR,
    fontSize: 15,
    color: COLORS.text,
    marginBottom: 20,
  },
  uploadModalFileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 22,
    height: 48,
    paddingHorizontal: 14,
    marginBottom: 20,
    backgroundColor: COLORS.white,
    gap: 10,
  },
  uploadModalFileSelectedText: {
    flex: 1,
    fontFamily: FONT_REGULAR,
    fontSize: 13,
    color: COLORS.text,
  },
  uploadModalValidateBtn: {
    backgroundColor: COLORS.orange,
    borderRadius: 22,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  uploadModalValidateBtnDisabled: {
    backgroundColor: '#D3D3D3',
  },
  uploadModalValidateBtnText: {
    fontFamily: FONT_SEMIBOLD,
    fontSize: 15,
    color: COLORS.white,
  },

  // ─── Health Field Selector Modal ──────────────────────────────────────────
  healthModalSheet: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
  },
  healthModalHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: COLORS.border,
    alignSelf: 'center',
    marginBottom: 16,
  },
  healthModalTitle: {
    fontFamily: FONT_SEMIBOLD,
    fontSize: 16,
    color: COLORS.text,
    textAlign: 'center',
    marginBottom: 16,
  },
  healthModalItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.background,
  },
  healthModalItemSelected: {
    backgroundColor: '#FFF5F0',
  },
  healthModalItemText: {
    fontFamily: FONT_REGULAR,
    fontSize: 15,
    color: COLORS.text,
  },
  healthModalItemTextSelected: {
    color: COLORS.orange,
    fontFamily: FONT_SEMIBOLD,
  },
});

