import { StyleSheet } from 'react-native';
import { COLORS, FONT_BOLD, FONT_REGULAR, FONT_SEMIBOLD } from '../Home/HomeScreen.styles';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: COLORS.background },
  container: { flex: 1, backgroundColor: COLORS.background },
  scrollContent: { padding: 15, paddingBottom: 100 },
  card: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 20,
    minHeight: 600,
  },
  title: {
    fontSize: 20,
    fontFamily: FONT_BOLD,
    color: COLORS.orange,
    textAlign: 'center',
    marginBottom: 30,
    textTransform: 'uppercase',
  },
  controlsContainer: { marginBottom: 20, zIndex: 10 },
  rowTop: { flexDirection: 'row', alignItems: 'center', marginBottom: 15 },
  label: { fontFamily: FONT_REGULAR, color: COLORS.textLight, marginRight: 10 },
  searchBox: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 20,
    paddingHorizontal: 12,
    height: 38,
    marginRight: 10,
  },
  searchInput: { flex: 1, fontSize: 12, color: '#333' },
  rightControl: { flexDirection: 'row', alignItems: 'center' },
  displayText: { fontSize: 11, color: '#999', marginRight: 5 },
  displayIcons: { flexDirection: 'row', gap: 6 },
  viewModeBtn: {
    width: 30,
    height: 30,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },

  rowBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 5
  },
  dropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 20,
    paddingLeft: 15,
    paddingRight: 5,
    height: 38,
    width: 140,
  },
  dropdownText: { fontSize: 13, color: '#666' },
  dropdownArrowBg: {
    backgroundColor: '#D3D3D3',
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dropdownList: {
    position: 'absolute',
    top: 42,
    left: 0,
    width: 140,
    backgroundColor: 'white',
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
  },
  dropdownItem: { padding: 10, borderBottomWidth: 1, borderBottomColor: '#F5F5F5' },
  dropdownItemText: { fontSize: 12, color: '#333' },

  addButton: {
    backgroundColor: '#F15A24',
    borderRadius: 20,
    paddingHorizontal: 15,
    height: 38,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 2,
  },
  addButtonText: { color: 'white', fontFamily: FONT_BOLD, fontSize: 12 },

  // TIMELINE
  timelineContainer: { marginTop: 20 },
  verticalLine: {
    position: 'absolute',
    left: '50%',
    top: 0,
    bottom: 0,
    width: 1,
    backgroundColor: '#D3D3D3',
  },
  timelineItem: { width: '50%', marginBottom: 30 },
  leftItem: { alignSelf: 'flex-start', paddingRight: 20 },
  rightItem: { alignSelf: 'flex-end', paddingLeft: 20 },
  timelineIconWrapper: {
    position: 'absolute',
    top: 10,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'white',
    borderWidth: 2,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
  },
  iconLeft: { right: -15, borderColor: COLORS.orange },
  iconRight: { left: -15, borderColor: '#3ABFBF' },
  itemContent: {
    padding: 12,
  },
   author: { fontSize: 11, fontWeight: 'bold', color: '#666' },
  dateText: { fontSize: 10, color: '#999', marginBottom: 5 },
  docTitle: { fontSize: 11, fontFamily: FONT_REGULAR, color: COLORS.textLight },
  docDesc: { fontSize: 11, color: '#444', marginTop: 3 },
  actionIcons: { flexDirection: 'row', gap: 8, marginTop: 12, alignItems: 'center', justifyContent: 'center' },
  timelineActionBtn: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // --- Modale d'ajout de document ---
  modalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 24,
    paddingBottom: 36,
  },
  modalTitle: {
    fontFamily: FONT_BOLD,
    fontSize: 18,
    color: COLORS.orange,
    textAlign: 'center',
    marginBottom: 24,
  },
  inputLabel: {
    fontFamily: FONT_SEMIBOLD,
    fontSize: 12,
    color: COLORS.textLight,
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    fontFamily: FONT_SEMIBOLD,
    fontSize: 13,
    color: COLORS.text,
    backgroundColor: '#F9F9F9',
  },
  uploadButtonModal: {
    backgroundColor: COLORS.orange,
    borderRadius: 22,
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 12,
  },
  uploadButtonTextModal: {
    fontFamily: FONT_SEMIBOLD,
    fontSize: 14,
    color: COLORS.white,
    flexShrink: 1,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 20,
    marginTop: 8,
  },
  // ── Modale de visualisation (centrée) ────────────────────────────────────
  viewModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  viewModalContent: {
    width: '100%',
    backgroundColor: COLORS.white,
    borderRadius: 20,
    padding: 24,
    elevation: 5,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  viewModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  viewModalTitle: {
    fontSize: 16,
    fontFamily: FONT_BOLD,
    color: COLORS.orange,
    textTransform: 'uppercase',
  },
  viewModalCloseBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1.5,
    borderColor: COLORS.text,
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewDetailTable: {
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  viewDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  viewDetailLabel: {
    flex: 1,
    fontSize: 12,
    fontFamily: FONT_SEMIBOLD,
    color: COLORS.textLight,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  viewDetailValue: {
    flex: 1.5,
    fontSize: 13,
    fontFamily: FONT_REGULAR,
    color: COLORS.text,
  },
  viewActionsSection: {
    marginTop: 20,
    paddingVertical: 10,
  },
  viewActionsLabel: {
    fontSize: 12,
    fontFamily: FONT_BOLD,
    color: COLORS.textLight,
    marginBottom: 15,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  viewBigActionsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 20,
  },
  viewBigActionButton: {
    width: 65,
    height: 65,
    backgroundColor: COLORS.offWhite,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    elevation: 1,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: 1 },
  },
  // Boutons originaux (au cas où tu en aurais encore besoin ailleurs, sinon tu peux les enlever)
  cancelButton: {
    flex: 1,
    padding: 15,
    alignItems: 'center',
    borderRadius: 8,
    backgroundColor: '#EEE',
    marginRight: 10
  },
  cancelButtonText: { color: '#333', fontWeight: 'bold' },
  saveButton: {
    flex: 1,
    padding: 15,
    alignItems: 'center',
    borderRadius: 8,
    backgroundColor: COLORS.orange,
    marginLeft: 10
  },
  saveButtonText: { color: 'white', fontWeight: 'bold' },

  // TABLEAU (VUE LISTE) - Unifié
  tableContainer: { marginTop: 20 },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#F0F0F0',
    padding: 10,
    borderRadius: 5
  },
  headerText: { fontSize: 10, fontFamily: FONT_BOLD, color: '#666' },
  tableRow: {
    flexDirection: 'row',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#EEE',
    alignItems: 'center'
  },
  rowText: { fontSize: 11, color: '#333' },
  rowActions: { flexDirection: 'row', gap: 15 },
  eyeCircle: { width: 28, height: 28, justifyContent: 'center', alignItems: 'center' },

  // Styles pour la Grille
  gridContainer: { marginTop: 20 },
  gridItem: { marginBottom: 25, padding: 10 },
  imagePlaceholder: { height: 200, backgroundColor: '#F9F9F9', borderRadius: 10, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: '#EEE' },
  gridCaption: { flexDirection: 'row', backgroundColor: '#E0E0E0', padding: 10, marginTop: 10, borderRadius: 5 },
  captionLabel: { flex: 1, fontSize: 12, fontFamily: FONT_REGULAR },
  captionValue: { flex: 1, fontSize: 12 },
});